Use C++17 (#13)
When building on electron 11.4.7 it fails with
error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?

Bumping to C++17 solves this